//
//  TabAllInteractor.swift
//  MobileGuideAppVIP
//
//  Created by AphiwitSCB on 1/9/2562 BE.
//  Copyright (c) 2562 OnceKB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabAllBusinessLogic
{
    func getDataAPI(request: TabAll.TableviewFeed.Request)
}

protocol TabAllDataStore
{
  var dataArray : [MobileList] { get set }
}

class TabAllInteractor: TabAllBusinessLogic, TabAllDataStore
{
 
  var presenter: TabAllPresentationLogic?
  var worker: TabAllWorker?
    
  var dataArray: [MobileList] = []
    
  //var name: String = ""
  // MARK: Do something
//  func doSomething(request: TabAll.Something.Request)
//  {
//    worker = TabAllWorker()
//    worker?.doSomeWork()
//    
//    let response = TabAll.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
    
    func getDataAPI(request: TabAll.TableviewFeed.Request) {
        worker = TabAllWorker()
    
        worker?.feedContent(completion: { (resultt) in
            self.dataArray = resultt
            print(self.dataArray)
           self.presenter?.presentDataArray()
            
        })
       
    }
}
