//
//  TabAllViewController.swift
//  MobileGuideAppVIP
//
//  Created by AphiwitSCB on 1/9/2562 BE.
//  Copyright (c) 2562 OnceKB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabAllDisplayLogic: class
{
//  func displaySomething(viewModel: TabAll.Something.ViewModel)
    func reloadTableViewData()
}

class TabAllViewController: UIViewController, TabAllDisplayLogic, UITableViewDelegate, UITableViewDataSource
{
    
  var interactor: (TabAllBusinessLogic & TabAllDataStore)?
  var router: (NSObjectProtocol & TabAllRoutingLogic & TabAllDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  private func setup()
  {
    let viewController = self
    let interactor = TabAllInteractor()
    let presenter = TabAllPresenter()
    let router = TabAllRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
//    doSomething()
    loadtableFromAPI()
    reloadTableViewData()
  }
    
    

  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  @IBOutlet weak var mainTableView: UITableView!
  
    
    
   func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return interactor?.dataArray.count ?? 0
    
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "tabAllCell") as? TabAllTableViewCell
        let item = interactor?.dataArray[indexPath.row]
        cell?.cellLabel.text = item?.name
        return cell!
    
    }
    
    func reloadTableViewData() {
        mainTableView.reloadData()
        print(mainTableView)
    }
    
    func loadtableFromAPI() {
        let request = TabAll.TableviewFeed.Request()
        interactor?.getDataAPI(request: request)
    }
    
    
    
 
  
  func displayData(viewModel: TabAll.TableviewFeed.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
