//
//  TabAllWorker.swift
//  MobileGuideAppVIP
//
//  Created by AphiwitSCB on 1/9/2562 BE.
//  Copyright (c) 2562 OnceKB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class TabAllWorker
{
    func feedContent(completion:  @escaping(_ result: [MobileList]) -> Void) {
        let baseUrl = "https://scb-test-mobile.herokuapp.com/api/mobiles"
        AF.request(baseUrl).response { (response) in
            do {
                let decoder = JSONDecoder()
                let result = try decoder.decode([MobileList].self, from: response.data!)
                completion(result)
            }catch {
                print("---error --->", error.localizedDescription)
            }
        }
    }
}
